### ISSUE TITLE
Facebook Login on iPhone fails/cancels

### ISSUE THREAD

**Issue by BrightRaven** [IlluminusLimited/CoreUI#17]
In the development app you go through the buttons to click "Log in with the Facebok app", then hit "Open" and it says you have previously logged in would you like to conntinue. When you say yes, it goes to a blank screen with cancel at the top and nothing happens.

**Comment by scytherswings** [comment]
I believe this was caused by me not setting up the facebook app correctly. Instructions were followed from https://docs.expo.io/versions/latest/sdk/facebook/

**Comment by scytherswings** [comment]
No longer an issue
