### ISSUE TITLE
Description section of collectable needs polish

### ISSUE THREAD

**Issue by BrightRaven** [IlluminusLimited/CoreUI#32]
The details section of the collectables is in plain text and is not the prettiest to look at. Need to add some styling.

**Comment by scytherswings** [comment]
The current details section is very plain right now. It's not completely unstyled but it could use some inspiration. Also we have to figure out how we're eventually going to display tags vs description. Descriptions should be english sentences. Tags should be used for things like "blue", "dragon" etc. 

Chips might be a good UI component to use for tags https://callstack.github.io/react-native-paper/chip.html
