### ISSUE TITLE
Main page loads less than three collectables on the bottom row

### ISSUE THREAD

**Issue by BrightRaven** [IlluminusLimited/CoreUI#33]
The main page on both android and iPhone loads one or two collectables in the bottom row just above the "Load More" button. Not sure if this is a true bug, but aesthetically it looks odd. Need to make the bottom row fill out with three collectables (or whichever number is appropriate for the number of columns - thinking iPad here), unless it is the end of the list.

**Comment by scytherswings** [comment]
I suppose it's a bug from the visual implementation, but if we want to fix it we'll have to render dummy containers to fill the other empty columns. You'll want to look up the styling settings I've used so far which would be `space-around`
