### ISSUE TITLE
No image loads but description does

### ISSUE THREAD

**Issue by BrightRaven** [IlluminusLimited/CoreUI#34]
Some of the images on the home screen are not loading. It seems nothing is there. This may be an issue with the profanity filter. If the image is rejected, it should not generate and load an info card.

**Comment by scytherswings** [comment]
This is because react native is weird about what images it will load from a url and the placeholder image is not one of them, so instead it just renders nothing. This is why we need to figure out the moderation and clean up the existing entries.

**Comment by scytherswings** [comment]
This is no longer an issue and was fixed in v1.0.x
