### ISSUE TITLE
Use carousels instead for the collectable page images

### ISSUE THREAD

**Issue by stretch1414** [IlluminusLimited/CoreUI#9]
We don't need an image grid for the collectable page images, we can just use a carousel.

https://github.com/archriss/react-native-snap-carousel
https://github.com/oliviertassinari/react-swipeable-views
https://github.com/react-native-community/react-native-tab-view
https://github.com/zachgibson/react-native-parallax-swiper

**Comment by scytherswings** [comment]
https://github.com/zachgibson/react-native-parallax-swiper/blob/master/examples/ParallaxSwiperExample/screens/Twitter/index.js

**Comment by scytherswings** [comment]
This is done
